### ISSUE TITLE
i-row嵌套问题

### ISSUE THREAD

**Issue by p2ng** [iview/iview-mpvue#13]
# Vue页面代码
```
<template>
  <i-row>
    <i-row>1</i-row>
    <i-row>2</i-row>
  </i-row>
</template>

<script>
  import iRow from 'iview-mpvue/dist/components/row/row'
  import iCol from 'iview-mpvue/dist/components/col/col'

  export default {
    components: {
      'i-row': iRow,
      'i-col': iCol
    }
  }
</script>

<style>
</style>
```

# 微信开发者工具控制台
```
VM3859:1 ./modules/iview-mpvue/dist/components/row/row.vue.wxml
./modules/iview-mpvue/dist/components/row/row.vue.wxml:-1:-1:-1: Template `./modules/iview-mpvue/dist/components/row/row.vue.wxml:33c54a79` is being called recursively, will be stop.
```
![image](https://user-images.githubusercontent.com/7822128/62049382-a907f480-b241-11e9-8e82-51a3f859f6e0.png)

# 问题
1. 有点不知所以的报错。可能写多了PC版的,,,转到小程序就不能这么嵌套写！？

**Comment by Dewyzee** [comment]
> # Vue页面代码
> ```
> <template>
>   <i-row>
>     <i-row>1</i-row>
>     <i-row>2</i-row>
>   </i-row>
> </template>
> 
> <script>
>   import iRow from 'iview-mpvue/dist/components/row/row'
>   import iCol from 'iview-mpvue/dist/components/col/col'
> 
>   export default {
>     components: {
>       'i-row': iRow,
>       'i-col': iCol
>     }
>   }
> </script>
> 
> <style>
> </style>
> ```
> 
> # 微信开发者工具控制台
> ```
> VM3859:1 ./modules/iview-mpvue/dist/components/row/row.vue.wxml
> ./modules/iview-mpvue/dist/components/row/row.vue.wxml:-1:-1:-1: Template `./modules/iview-mpvue/dist/components/row/row.vue.wxml:33c54a79` is being called recursively, will be stop.
> ```
> 
> ![image](https://user-images.githubusercontent.com/7822128/62049382-a907f480-b241-11e9-8e82-51a3f859f6e0.png)
> 
> # 问题
> 1. 有点不知所以的报错。可能写多了PC版的,,,转到小程序就不能这么嵌套写！？

mpvue会把组件编译为单独的template，然后通过import引入，这样嵌套会导致模板内部引用自己本身，在小程序内部会形成循环依赖，暂时不建议这样使用
